# Generated by Django 3.1.1 on 2020-09-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('venue', models.CharField(max_length=130)),
                ('manager', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
